[package]
name = "telegram-bot-api-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
tokio = { version = "1.45.1", features = ["fs"] }
futures = "0.3.31"
tokio-util = "0.7.15"
mime_guess = "2.0.5"
futures-core = "0.3.31"
awc = "3.7.0"
futures-util = "0.3.31"
