services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    env_file:
      - path: .env
        required: true
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    restart: always
    ports:
      - "8081:8081"

  telegram-bot-api-proxy:
    image: ghcr.io/raphtlw/telegram-bot-api:main
    build: .
    container_name: telegram-bot-api-proxy
    env_file:
      - path: .env
        required: true
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    develop:
      watch:
        - path: .
          action: rebuild
    restart: always
    ports:
      - "3000:3000"

volumes:
  telegram-bot-api-data:
